### ISSUE TITLE
Thank you for sharing this work :)

### ISSUE THREAD

**Issue by asigalov61** [ilya16/ScorePerformer#1]
@ilya16 Hey Ilya!

Thank you for the follow and thank you for sharing your work. I saw your paper on ISMIR (congrats) and I am happy to see the code and colab on GitHub.

I will be checking it out soon and I have some questions for you. Please watch out for my email as I would prefer to discuss stuff in private rather than here.

Anyway, hope to talk to you soon.

Alex

P.S. You can close this issue. I just wanted to say hi.

**Comment by ilya16** [comment]
Hi and thanks, Alex! :) 

Replied to your email. Hope to hear from you soon.
